### ISSUE TITLE
Chapter 05 configure.cpp incorrect.

### ISSUE THREAD

**Issue by gpollice** [PacktPublishing/Modern-CMake-for-Cpp#1]
The book is correct, but the configure.spp that is in this project is not. You show in the book:

  cout << "FOO_ENABLE1: " << xstr(FOO_STRING1) << endl;
  cout << "FOO_ENABLE2: " << xstr(FOO_STRING2) << endl;

This works. However in the code here you have:
  cout << "FOO_ENABLE1: " << xstr(FOO_ENABLE1) << endl;
  cout << "FOO_ENABLE2: " << xstr(FOO_ENABLE2) << endl;

This does not work.

**Comment by Drakemor** [comment]
Thank you for pointing this out. I've submitted a correction in the latest [commit](https://github.com/PacktPublishing/Modern-CMake-for-Cpp/commit/c5c948747935b97f91ab9d391d1c9c2a0655b038).
