### ISSUE TITLE
Evaluation of conditional expressions

### ISSUE THREAD

**Issue by telzhov** [PacktPublishing/Modern-CMake-for-Cpp#4]
Chapter 2, Understanding control structures in CMake, Conditional blocks, The evaluation of a string and a variable:

```
set(VAR1 FALSE)
set(VAR2 "VAR1")
if(${VAR2})
```
_The if() condition works in a bit of a convoluted way here – first, it will evaluate
${VAR2} to VAR1, **which is a recognized variable, and this in turn is evaluated to the
FALSE string.**_

The CMake manual, on the other hand, [states](https://cmake.org/cmake/help/latest/command/if.html):

`if(<variable>)
`

_True if given a variable that is defined to a value that is not a false constant. False otherwise, including if the variable is undefined._

Nothing about checking if the value matches any of the visible variable names, to evaluate it in turn.

So could you clarify, what exactly did you mean here?

Thanks!

**Comment by Drakemor** [comment]
Sure! The documentation is really bad at explaining the actual logic, but we can break it down together.
Let's figure out what does this sentence mean.
1. Only state where we can get true with <variable> is where the value stored in the variable is "not a false constant". 
2. False constants are defined in the documentation as: 0, OFF, NO, FALSE, N, IGNORE, NOTFOUND, the empty string, or ends in the suffix -NOTFOUND...
**3. Important! Reading further: If the argument is not one of these specific constants, it is treated as a variable or string**
4. Variable is just a recursive call to step 1, for other cases go to step 5
5. String is false unless it is "a true constant" (which is  1, ON, YES, TRUE, Y, or a non-zero number)

My explanation in the book is simplified form of the above.
